### ISSUE TITLE
ScanningExpection: Unknown character

### ISSUE THREAD

**Issue by sachaarbonel** [simolus3/build_ffi_generator#1]
Hi @simolus3, I wanted to try out your library on bindings I could'nt figure out how to make properly and it failed on those:
```c
typedef struct {
  int64_t len;
  uint8_t *data;
} ByteBuffer;

ByteBuffer get_address_book(void);

void mylib_destroy_bytebuffer(ByteBuffer v);
```
with this error message : 
```bash
[SEVERE] build_ffi_generator:build_ffi_generator on example/addressbook.ffi.txt:

ScanningExpection: Unknown character at <FileLocation: 16 asset:build_ffi_generator/example/addressbook.ffi.txt:1:17>, Unknown character at <FileLocation: 50 asset:build_ffi_generator/example/addressbook.ffi.txt:4:2>
[INFO] Running build completed, took 125ms
[INFO] Caching finalized dependency graph completed, took 112ms
[SEVERE] Failed after 281ms
```

**Comment by simolus3** [comment]
Thanks for trying this out. I should note that I mostly wrote this for personal use, so I probably won't polish the library that much. The Dart team has someone working on a proper tool (https://dartbug.com/35843), so this is mostly a temporary hack to make things easier.

I didn't implement structs yet, but it shouldn't be much work. I'll take a look at them this evening :)

**Comment by simolus3** [comment]
I've added support for structs in df80147482f95e0171a6cd1923e783ec95bd3a76.

The syntax is slightly different to make parsing easier:

```c
type ByteBuffer = struct {
    int64 len;
    uint8 *data;
};

ByteBuffer get_address_book();
void mylib_destroy_bytebuffer(ByteBuffer v);
```

**Comment by sachaarbonel** [comment]
Thank's a lot! Interestingly this is what I came up with my manual [bindings](https://github.com/sachaarbonel/rusty_json_ffi.dart/blob/protobuf/bin/main.dart). I guess I need to figure it how I can access the underlying List<int> to construct my protobuf

**Comment by simolus3** [comment]
> I guess I need to figure it how I can access the underlying List to construct my protobuf

Do you mean this?

```dart
extension on ByteBuffer {
  Uint8List get asList => data.asTypedList(len);
}
```

**Comment by sachaarbonel** [comment]
Yeah exactly this but unfortunately it segfault
